Base:
  model_root: '../checkpoints/'  # 日志和模型存放地
  num_workers: 3
  verbose: 1
  patience: 2
  pickle_feature_encoder: True
  use_hdf5: True
  save_best_only: True
  every_x_epochs: 1
  debug: False
  partition_block_size: -1
  gpu: 0



DeepFM_base:
  model_id: DeepFM_demo
  model_name: DeepFM
  loss: 'binary_crossentropy'
  metrics: [ 'logloss', 'AUC' ]
  task: binary_classification
  optimizer: adam
  learning_rate: 1.e-3
  batch_size: 1024
  epochs: 1
  shuffle: True
  seed: 20001
  rand_number: 20001
  monitor: { 'AUC': 1, 'logloss': -1 }
  monitor_mode: 'max'
  dnn_hidden_units: [ 64, 64, 64 ]
  hidden_activations: relu
  net_regularizer: 0
  embedding_regularizer: 0
  net_dropout: 0
  embedding_dim: 16
  batch_norm: False


