Base:
  model_root: '../checkpoints/'  # 日志和模型存放地
  num_workers: 3
  verbose: 1
  patience: 2
  pickle_feature_encoder: True
  use_hdf5: True
  save_best_only: True
  every_x_epochs: 1
  debug: False
  partition_block_size: -1


DeepFmFM_base:
  model_id: DeepFmFM_demo
  dataset_id: criteo_demo  # 新建的，checkpoints/+下日志和模型文件夹名，yml数据集名，data/+下保存的h5数据集
  loss: 'binary_crossentropy'   # 分类问题
  metrics: [ 'logloss', 'AUC' ]
  task: binary_classification
  optimizer: adam
  learning_rate: 1.0e-3
  embedding_regularizer: 0
  net_regularizer: 0
  batch_size: 16
  embedding_dim: 10
  dnn_activations: relu
  crossing_layers: 3
  net_dropout: 0
  batch_norm: False
  epochs: 3
  shuffle: True
  seed: 2022
  monitor: { 'AUC': 1, 'logloss': -1 }
  monitor_mode: 'max'
  field_interaction_type: 'matrixed'   # 特有的
