Base:
  model_root: '../checkpoints/'  # 日志和模型存放地
  num_workers: 3
  verbose: 1
  patience: 2
  pickle_feature_encoder: True
  use_hdf5: True
  save_best_only: True
  every_x_epochs: 1
  debug: False
  partition_block_size: -1
  gpu: -1



DNN_base:
  model_id: DNN_demo
  dataset_id: tiny_data_demo
  loss: 'binary_crossentropy'
  metrics: [ 'logloss', 'AUC' ]
  task: binary_classification
  optimizer: adam
  learning_rate: 1.e-3
  embedding_regularizer: 0
  net_regularizer: 0
  batch_size: 32
  embedding_dim: 10
  dnn_hidden_units: [ 64, 64, 64 ]
  hidden_activations: relu
  net_dropout: 0
  batch_norm: False
  epochs: 3
  shuffle: True
  seed: 2022
  monitor: { 'AUC': 1, 'logloss': -1 }
  monitor_mode: 'max'
