Base:
  model_root: '../checkpoints/'  # 日志和模型存放地
  num_workers: 3
  verbose: 1
  patience: 2
  pickle_feature_encoder: True
  use_hdf5: True
  save_best_only: True
  every_x_epochs: 1
  debug: False
  partition_block_size: -1
  gpu: 0



SAM_base:
  model_id: SAM_demo
  dataset_id: criteo_1w_demo
  loss: 'binary_crossentropy'
  metrics: [ 'logloss', 'AUC' ]
  task: binary_classification
  optimizer: adam
  learning_rate: 1.e-3
  embedding_regularizer: 0
  net_regularizer: 0
  batch_size: 4096
  rand_number: 10001
  embedding_dim: 40
  interaction_type: "SAM3E"
  aggregation: "concat"
  num_interaction_layers: 3
  use_residual: False
  net_dropout: 0
  epochs: 3
  shuffle: True
  seed: 2022
  monitor: 'AUC'
  monitor_mode: 'max'