### Criteo dataset
movie_1m_demo:
  data_root: ../data/
  data_format: csv
  all_data: ../data/ml-1m/movie1m.csv
  valid_size: 0.1
  test_size: 0.1
  min_categr_count: 2
  data_block_size: -1
  feature_cols:
    - { name: userId, active: True, dtype: str, type: categorical }
    - { name: gender, active: True, dtype: str, type: categorical }
    - { name: age, active: True, dtype: str, type: categorical }
    - { name: occupation, active: True, dtype: str, type: categorical }
    - { name: movieId, active: True, dtype: str, type: categorical }
    - { name: genres, active: True, dtype: str, type: sequence, splitter: '|' }

  label_col: { name: rating, dtype: float }